export const productsData = [
  {
    id: 1,
    title: "our first T-shirts",
    quantity: 1,
    descrption: "dark grey",
    availableSize: ["S", "L", "XL"],
    price: 10,
    isFreeShipping: true,
  },
  {
    id: 2,
    title: "our second T-shirts",
    quantity: 1,
    descrption: " grey",
    availableSize: ["S", "XL", "M"],
    price: 12,
    isFreeShipping: true,
  },
  {
    id: 3,
    title: "our third T-shirts",
    quantity: 1,
    descrption: "black",
    availableSize: ["S"],
    price: 19,
    isFreeShipping: true,
  },
  {
    id: 4,
    title: "our fourth T-shirts",
    quantity: 1,
    descrption: "darl blue",
    availableSize: ["XL"],
    price: 16,
    isFreeShipping: true,
  },
  {
    id: 5,
    title: "our fith T-shirts",
    quantity: 1,
    descrption: "dark grey",
    availableSize: ["S", "L", "XL", "XXL"],
    price: 22,
    isFreeShipping: false,
  },
  {
    id: 6,
    title: "our sixth T-shirts",
    quantity: 1,
    descrption: "orange",
    availableSize: ["M"],
    price: 18,
    isFreeShipping: false,
  },
  {
    id: 7,
    title: "our seventh T-shirts",
    quantity: 1,
    descrption: "light blue",
    availableSize: ["XS", "S", "L", "XL"],
    price: 59,
    isFreeShipping: false,
  },
  {
    id: 8,
    title: "our first T-shirts",
    quantity: 1,
    descrption: "red",
    availableSize: ["S", "XL"],
    price: 25,
    isFreeShipping: false,
  },
  {
    id: 9,
    title: "our nineth T-shirts",
    quantity: 1,
    descrption: "dark",
    availableSize: ["XS"],
    price: 10,
    isFreeShipping: false,
  },
];
